###############################################################################
# PURITY-ADJUSTED IMMUNE SENSITIVITY ANALYSIS
# LSCC MYBL2 reproducible analysis
#
# This script uses the ssGSEA and ESTIMATE outputs generated by
# 03_immune_microenvironment_analysis.R. It evaluates associations between
# MYBL2 expression and immune-cell enrichment before adjustment, after
# adjustment for ESTIMATE-derived tumor purity, and after adjustment for both
# tumor purity and dataset identity.
###############################################################################

rm(list = ls())
gc()

options(stringsAsFactors = FALSE, scipen = 100)

# -----------------------------------------------------------------------------
# 01. PATHS AND SETTINGS
# -----------------------------------------------------------------------------

RESULTS_PATH <- "E:/LSCC/Results_LSCC/ML"
IMMUNE_INPUT_DIR <- file.path(RESULTS_PATH, "Immune_Microenvironment_Analysis")
OUTPUT_DIR <- file.path(RESULTS_PATH, "Purity_Adjusted_Immune_Sensitivity")

SSGSEA_FILE <- file.path(
  IMMUNE_INPUT_DIR,
  "ssGSEA_28_immune_cell_scores_tumor_samples.csv"
)

ESTIMATE_FILE <- file.path(
  IMMUNE_INPUT_DIR,
  "ESTIMATE_scores_nonlog_TMM_CPM_no_batch_correction_tumor_samples.csv"
)

FDR_CUTOFF <- 0.05
ESTIMATE_PURITY_INTERCEPT <- 0.6049872018
ESTIMATE_PURITY_SLOPE <- 0.0001467884

dir.create(OUTPUT_DIR, recursive = TRUE, showWarnings = FALSE)

# -----------------------------------------------------------------------------
# 02. PACKAGES
# -----------------------------------------------------------------------------

required_packages <- c("dplyr", "tidyr", "tibble")
missing_packages <- required_packages[
  !vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)
]

if (length(missing_packages) > 0) {
  stop(
    "Missing required package(s): ",
    paste(missing_packages, collapse = ", "),
    "\nPlease install them before running this script."
  )
}

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(tibble)
})

# -----------------------------------------------------------------------------
# 03. HELPERS
# -----------------------------------------------------------------------------

safe_spearman <- function(x, y) {
  x <- suppressWarnings(as.numeric(as.character(x)))
  y <- suppressWarnings(as.numeric(as.character(y)))
  keep <- is.finite(x) & is.finite(y)

  if (sum(keep) < 5 || length(unique(x[keep])) < 2 ||
      length(unique(y[keep])) < 2) {
    return(data.frame(
      n = sum(keep),
      rho = NA_real_,
      p_value = NA_real_
    ))
  }

  test <- suppressWarnings(
    stats::cor.test(x[keep], y[keep], method = "spearman", exact = FALSE)
  )

  data.frame(
    n = sum(keep),
    rho = as.numeric(test$estimate),
    p_value = as.numeric(test$p.value)
  )
}

partial_spearman <- function(x, y, covariates) {
  x <- suppressWarnings(as.numeric(as.character(x)))
  y <- suppressWarnings(as.numeric(as.character(y)))
  covariates <- as.data.frame(
    covariates,
    check.names = FALSE,
    stringsAsFactors = FALSE
  )

  dat <- data.frame(
    X = x,
    Y = y,
    covariates,
    check.names = FALSE,
    stringsAsFactors = FALSE
  )

  numeric_columns <- vapply(dat, is.numeric, logical(1))
  finite_rows <- rep(TRUE, nrow(dat))

  for (column in names(dat)[numeric_columns]) {
    finite_rows <- finite_rows & is.finite(dat[[column]])
  }

  dat <- dat[stats::complete.cases(dat) & finite_rows, , drop = FALSE]

  empty_result <- function(n = nrow(dat)) {
    data.frame(
      n = n,
      partial_rho = NA_real_,
      p_value = NA_real_,
      df = NA_real_,
      covariate_df = NA_real_
    )
  }

  if (nrow(dat) < 6 || length(unique(dat$X)) < 2 ||
      length(unique(dat$Y)) < 2) {
    return(empty_result())
  }

  dat$X_rank <- rank(dat$X, ties.method = "average")
  dat$Y_rank <- rank(dat$Y, ties.method = "average")

  covariates_ranked <- data.frame(row.names = seq_len(nrow(dat)))

  for (column in colnames(covariates)) {
    value <- dat[[column]]

    if (is.numeric(value)) {
      if (length(unique(value)) >= 2) {
        covariates_ranked[[column]] <- rank(value, ties.method = "average")
      }
    } else {
      value <- factor(value)
      if (nlevels(value) >= 2) {
        covariates_ranked[[column]] <- value
      }
    }
  }

  if (ncol(covariates_ranked) == 0) {
    raw_result <- safe_spearman(dat$X, dat$Y)
    return(data.frame(
      n = nrow(dat),
      partial_rho = raw_result$rho,
      p_value = raw_result$p_value,
      df = nrow(dat) - 2,
      covariate_df = 0
    ))
  }

  model_data <- data.frame(
    X_rank = dat$X_rank,
    Y_rank = dat$Y_rank,
    covariates_ranked,
    check.names = FALSE
  )

  covariate_formula <- paste(colnames(covariates_ranked), collapse = " + ")
  model_x <- stats::lm(
    stats::as.formula(paste("X_rank ~", covariate_formula)),
    data = model_data
  )
  model_y <- stats::lm(
    stats::as.formula(paste("Y_rank ~", covariate_formula)),
    data = model_data
  )

  residual_x <- stats::residuals(model_x)
  residual_y <- stats::residuals(model_y)
  partial_rho <- suppressWarnings(
    stats::cor(residual_x, residual_y, method = "pearson")
  )

  model_matrix <- stats::model.matrix(
    stats::as.formula(paste("~", covariate_formula)),
    data = model_data
  )
  covariate_df <- qr(model_matrix)$rank - 1L
  test_df <- nrow(model_data) - covariate_df - 2L

  if (!is.finite(partial_rho) || test_df <= 0) {
    p_value <- NA_real_
  } else if (abs(partial_rho) >= 1) {
    p_value <- 0
  } else {
    statistic <- partial_rho * sqrt(test_df / (1 - partial_rho^2))
    p_value <- 2 * stats::pt(-abs(statistic), df = test_df)
  }

  data.frame(
    n = nrow(model_data),
    partial_rho = partial_rho,
    p_value = p_value,
    df = test_df,
    covariate_df = covariate_df
  )
}

# -----------------------------------------------------------------------------
# 04. LOAD INPUTS
# -----------------------------------------------------------------------------

missing_files <- c(SSGSEA_FILE, ESTIMATE_FILE)[
  !file.exists(c(SSGSEA_FILE, ESTIMATE_FILE))
]

if (length(missing_files) > 0) {
  stop(
    "Required input file(s) not found:\n",
    paste(missing_files, collapse = "\n"),
    "\nRun 03_immune_microenvironment_analysis.R first."
  )
}

ssgsea_scores <- as.matrix(
  utils::read.csv(
    SSGSEA_FILE,
    row.names = 1,
    check.names = FALSE
  )
)
storage.mode(ssgsea_scores) <- "numeric"

estimate_scores <- utils::read.csv(
  ESTIMATE_FILE,
  check.names = FALSE
)

required_estimate_columns <- c(
  "Sample", "Dataset", "MYBL2_expression",
  "Stromal_score", "Immune_score", "ESTIMATE_score"
)

if (!all(required_estimate_columns %in% colnames(estimate_scores))) {
  stop(
    "The ESTIMATE input is missing required columns: ",
    paste(
      setdiff(required_estimate_columns, colnames(estimate_scores)),
      collapse = ", "
    )
  )
}

if (is.null(rownames(ssgsea_scores)) || is.null(colnames(ssgsea_scores))) {
  stop("The ssGSEA matrix must contain immune-cell row names and sample columns.")
}

# -----------------------------------------------------------------------------
# 05. DERIVE ESTIMATE-BASED TUMOR PURITY
# -----------------------------------------------------------------------------

estimate_scores$Tumor_Purity_ESTIMATE <- cos(
  ESTIMATE_PURITY_INTERCEPT +
    ESTIMATE_PURITY_SLOPE * estimate_scores$ESTIMATE_score
)

invalid_purity <- !is.finite(estimate_scores$Tumor_Purity_ESTIMATE) |
  estimate_scores$Tumor_Purity_ESTIMATE < 0 |
  estimate_scores$Tumor_Purity_ESTIMATE > 1

if (any(invalid_purity)) {
  stop("Non-finite or out-of-range ESTIMATE-derived purity values detected.")
}

utils::write.csv(
  estimate_scores,
  file.path(OUTPUT_DIR, "ESTIMATE_derived_tumor_purity_per_sample.csv"),
  row.names = FALSE
)

mybl2_purity <- safe_spearman(
  estimate_scores$MYBL2_expression,
  estimate_scores$Tumor_Purity_ESTIMATE
)

utils::write.csv(
  mybl2_purity,
  file.path(OUTPUT_DIR, "MYBL2_vs_tumor_purity_Spearman.csv"),
  row.names = FALSE
)

# -----------------------------------------------------------------------------
# 06. PREPARE IMMUNE-CELL SCORES
# -----------------------------------------------------------------------------

immune_long <- as.data.frame(t(ssgsea_scores), check.names = FALSE) %>%
  tibble::rownames_to_column("Sample") %>%
  tidyr::pivot_longer(
    cols = -Sample,
    names_to = "Immune_cell",
    values_to = "ssGSEA_score"
  ) %>%
  dplyr::left_join(
    estimate_scores %>%
      dplyr::select(
        Sample,
        Dataset,
        MYBL2_expression,
        Tumor_Purity_ESTIMATE
      ),
    by = "Sample"
  )

if (anyNA(immune_long$MYBL2_expression) ||
    anyNA(immune_long$Tumor_Purity_ESTIMATE)) {
  stop("Sample identifiers do not match between ssGSEA and ESTIMATE inputs.")
}

# -----------------------------------------------------------------------------
# 07. RAW, PURITY-ADJUSTED, AND DATASET-ADJUSTED ASSOCIATIONS
# -----------------------------------------------------------------------------

immune_results <- lapply(
  unique(immune_long$Immune_cell),
  function(cell_name) {
    data_cell <- immune_long[immune_long$Immune_cell == cell_name, , drop = FALSE]

    raw_result <- safe_spearman(
      data_cell$MYBL2_expression,
      data_cell$ssGSEA_score
    )
    purity_result <- partial_spearman(
      data_cell$MYBL2_expression,
      data_cell$ssGSEA_score,
      data.frame(Tumor_Purity_ESTIMATE = data_cell$Tumor_Purity_ESTIMATE)
    )
    sensitivity_result <- partial_spearman(
      data_cell$MYBL2_expression,
      data_cell$ssGSEA_score,
      data.frame(
        Tumor_Purity_ESTIMATE = data_cell$Tumor_Purity_ESTIMATE,
        Dataset = data_cell$Dataset
      )
    )

    data.frame(
      Immune_cell = cell_name,
      Raw_N = raw_result$n,
      Raw_Spearman_Rho = raw_result$rho,
      Raw_P_Value = raw_result$p_value,
      Purity_Adjusted_N = purity_result$n,
      Purity_Adjusted_df = purity_result$df,
      Purity_Adjusted_Partial_Rho = purity_result$partial_rho,
      Purity_Adjusted_P_Value = purity_result$p_value,
      Purity_Dataset_Adjusted_N = sensitivity_result$n,
      Purity_Dataset_Adjusted_df = sensitivity_result$df,
      Purity_Dataset_Adjusted_Partial_Rho = sensitivity_result$partial_rho,
      Purity_Dataset_Adjusted_P_Value = sensitivity_result$p_value
    )
  }
) %>%
  dplyr::bind_rows() %>%
  dplyr::mutate(
    Raw_BH_FDR = stats::p.adjust(Raw_P_Value, method = "BH"),
    Purity_Adjusted_BH_FDR = stats::p.adjust(
      Purity_Adjusted_P_Value,
      method = "BH"
    ),
    Purity_Dataset_Adjusted_BH_FDR = stats::p.adjust(
      Purity_Dataset_Adjusted_P_Value,
      method = "BH"
    ),
    Raw_Significant = is.finite(Raw_BH_FDR) & Raw_BH_FDR < FDR_CUTOFF,
    Purity_Adjusted_Significant = is.finite(Purity_Adjusted_BH_FDR) &
      Purity_Adjusted_BH_FDR < FDR_CUTOFF,
    Purity_Dataset_Adjusted_Significant =
      is.finite(Purity_Dataset_Adjusted_BH_FDR) &
      Purity_Dataset_Adjusted_BH_FDR < FDR_CUTOFF
  ) %>%
  dplyr::arrange(Purity_Dataset_Adjusted_BH_FDR)

utils::write.csv(
  immune_results,
  file.path(
    OUTPUT_DIR,
    "MYBL2_immune_raw_purity_and_dataset_adjusted_results.csv"
  ),
  row.names = FALSE
)

# -----------------------------------------------------------------------------
# 08. ESTIMATE COMPONENT SENSITIVITY
# -----------------------------------------------------------------------------

estimate_component_results <- lapply(
  c("Immune_score", "Stromal_score"),
  function(score_name) {
    raw_result <- safe_spearman(
      estimate_scores$MYBL2_expression,
      estimate_scores[[score_name]]
    )
    purity_result <- partial_spearman(
      estimate_scores$MYBL2_expression,
      estimate_scores[[score_name]],
      data.frame(
        Tumor_Purity_ESTIMATE = estimate_scores$Tumor_Purity_ESTIMATE
      )
    )
    sensitivity_result <- partial_spearman(
      estimate_scores$MYBL2_expression,
      estimate_scores[[score_name]],
      data.frame(
        Tumor_Purity_ESTIMATE = estimate_scores$Tumor_Purity_ESTIMATE,
        Dataset = estimate_scores$Dataset
      )
    )

    data.frame(
      Score = score_name,
      Raw_N = raw_result$n,
      Raw_Spearman_Rho = raw_result$rho,
      Raw_P_Value = raw_result$p_value,
      Purity_Adjusted_Partial_Rho = purity_result$partial_rho,
      Purity_Adjusted_P_Value = purity_result$p_value,
      Purity_Dataset_Adjusted_Partial_Rho = sensitivity_result$partial_rho,
      Purity_Dataset_Adjusted_P_Value = sensitivity_result$p_value
    )
  }
) %>%
  dplyr::bind_rows() %>%
  dplyr::mutate(
    Raw_BH_FDR = stats::p.adjust(Raw_P_Value, method = "BH"),
    Purity_Adjusted_BH_FDR = stats::p.adjust(
      Purity_Adjusted_P_Value,
      method = "BH"
    ),
    Purity_Dataset_Adjusted_BH_FDR = stats::p.adjust(
      Purity_Dataset_Adjusted_P_Value,
      method = "BH"
    )
  )

utils::write.csv(
  estimate_component_results,
  file.path(OUTPUT_DIR, "ESTIMATE_component_sensitivity_results.csv"),
  row.names = FALSE
)

# -----------------------------------------------------------------------------
# 09. SAVE ANALYSIS OBJECTS AND SESSION INFORMATION
# -----------------------------------------------------------------------------

saveRDS(
  list(
    immune_results = immune_results,
    estimate_component_results = estimate_component_results,
    mybl2_purity = mybl2_purity,
    estimate_scores = estimate_scores
  ),
  file.path(OUTPUT_DIR, "purity_adjusted_immune_sensitivity_results.rds")
)

writeLines(
  capture.output(utils::sessionInfo()),
  file.path(OUTPUT_DIR, "sessionInfo.txt")
)

cat("\nPURITY-ADJUSTED IMMUNE SENSITIVITY ANALYSIS FINISHED\n")
cat("Outputs saved to:\n", OUTPUT_DIR, "\n", sep = "")

# End of script
